AuditorBundle\Entity\Comment:
    type: entity
    table: comment
    indexes:
        file_id:
            columns:
                - file_id
        author_id:
            columns:
                - author_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        added:
            type: datetime
            nullable: false
    manyToOne:
        file:
            targetEntity: File
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                file_id:
                    referencedColumnName: id
            orphanRemoval: false
        author:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
