AuditorBundle\Entity\File:
    type: entity
    table: file
    indexes:
        project_id:
            columns:
                - project_id
        content_id:
            columns:
                - content_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        added:
            type: datetime
            nullable: false
    manyToOne:
        project:
            targetEntity: Project
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
        content:
            targetEntity: Project
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                content_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
