AuditorBundle\Entity\Project:
    type: entity
    table: project
    indexes:
        owner_id:
            columns:
                - owner_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        added:
            type: datetime
            nullable: false
    manyToOne:
        owner:
            targetEntity: User
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                owner_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
