AuditorBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        displayName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: display_name
    lifecycleCallbacks: {  }
