parameters:

services:
  app.command_handler_resolver:
    class: CqrsBundle\SymfonyCommandHandlerResolver
    arguments: ["@service_container"]

  app.command_bus:
    class: CqrsBundle\CommandBus
    arguments: ["@app.command_handler_resolver"]

  app.command_handler.create_new_project:
    class: AppBundle\Command\Handler\CreateNewProjectHandler
