parameters:

services:
  app.command_handler_resolver:
    class: CqrsBundle\SymfonyCommandHandlerResolver
    arguments: ["@service_container"]

  app.command_bus:
    class: CqrsBundle\CommandBus
    arguments: ["@app.command_handler_resolver"]

  app.command_handler.create_new_project:
    class: AppBundle\Command\Handler\CreateNewProjectHandler
    arguments: ["@app.repository.project"]

  app.repository.project:
    class: AppBundle\Repository\Doctrine\ProjectRepositoryDoctrine
    arguments: ["@doctrine.orm.entity_manager"]