parameters:

services:
  app.exception_listener:
    class: AppBundle\EventListener\ExceptionListener
    arguments: ["@kernel"]
    tags:
        - { name: kernel.event_listener, event: kernel.exception }

  app.command_handler_resolver:
    class: AppBundle\Adapter\SymfonyCommandHandlerResolver
    arguments: ["@service_container"]

  app.event_bus:
    class: AppBundle\Adapter\SymfonyEventBus
    arguments: ["@event_dispatcher"]

  app.query_dispatcher:
    class: AppBundle\Adapter\DbalQueryDispatcher
    arguments: ["@doctrine.dbal.default_connection"]

  app.command_bus:
    class: CqrsBundle\Commanding\CommandBus
    arguments: ["@app.command_handler_resolver", "@app.event_bus"]

  app.service.auth:
    class: AppBundle\Service\AuthService

  app.event_listener.log:
    class: AppBundle\EventSubscriber\LogEventSubscriber
    arguments: ["%kernel.logs_dir%"]
    tags:
      - { name: kernel.event_subscriber }

  app.repository.project:
    class: AppBundle\Repository\ProjectDoctrineRepository
    arguments: ["@doctrine.orm.entity_manager"]

  app.repository.user:
    class: AppBundle\Repository\UserDoctrineRepository
    arguments: ["@doctrine.orm.entity_manager"]

  app.command_handler.create_new_project:
    class: AuditorBundle\Command\Handler\CreateNewProjectHandler
    arguments: ["@app.event_bus", "@app.repository.project", "@app.repository.user"]