parameters:

services:
  app.command_handler_resolver:
    class: AppBundle\SymfonyCommandHandlerResolver
    arguments: ["@service_container"]

  app.event_bus:
    class: AppBundle\SymfonyEventBus
    arguments: ["@app.command_handler_resolver"]

  app.command_bus:
    class: CqrsBundle\Commanding\CommandBus
    arguments: ["@app.command_handler_resolver", "@app.event_bus"]

  app.command_handler.create_new_project:
    class: AuditorBundle\Command\Handler\CreateNewProjectHandler
    arguments: ["@app.event_bus", "@app.repository.project"]

  app.repository.project:
    class: AppBundle\Repository\ProjectDoctrineRepository
    arguments: ["@doctrine.orm.entity_manager"]