parserOptions:
  ecmaVersion: 6
rules:
  indent:
    - 2
    - 4
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - windows
  semi:
    - 2
    - always
  no-irregular-whitespace:
    - 0
  no-unused-vars:
    - 2
    - args: after-used
      argsIgnorePattern: ^_
env:
  es6: true
  browser: true
extends: 'eslint:recommended'
